In [1]:
print("My analysis notebook")

My analysis notebook

In [2]:
file = open('cars.csv')

lines = file.readlines()

file.close()

for line in lines[:5]:
    print(line.strip())

for line in lines[1:6]:
    row = line.strip().split(',')
    print(row)

for line in lines[1:]:
    row = line.strip().split(',')

    mpg = float(row[7])

    if mpg > 30:
        print(row[0], mpg)

"Dimensions.Height","Dimensions.Length","Dimensions.Width","Engine Information.Driveline","Engine Information.Engine Type","Engine Information.Hybrid","Engine Information.Number of Forward Gears","Engine Information.Transmission","Fuel Information.City mpg","Fuel Information.Fuel Type","Fuel Information.Highway mpg","Identification.Classification","Identification.ID","Identification.Make","Identification.Model Year","Identification.Year","Engine Information.Engine Statistics.Horsepower","Engine Information.Engine Statistics.Torque"
"140","143","202","All-wheel drive","Audi 3.2L 6 cylinder 250hp 236ft-lbs","True","6","6 Speed Automatic Select Shift","18","Gasoline","25","Automatic transmission","2009 Audi A3 3.2","Audi","2009 Audi A3","2009","250","236"
"140","143","202","Front-wheel drive","Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo","True","6","6 Speed Automatic Select Shift","22","Gasoline","28","Automatic transmission","2009 Audi A3 2.0 T AT","Audi","2009 Audi A3","2009","200","207"
"140","143","202","Front-wheel drive","Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo","True","6","6 Speed Manual","21","Gasoline","30","Manual transmission","2009 Audi A3 2.0 T","Audi","2009 Audi A3","2009","200","207"
"140","143","202","All-wheel drive","Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo","True","6","6 Speed Automatic Select Shift","21","Gasoline","28","Automatic transmission","2009 Audi A3 2.0 T Quattro","Audi","2009 Audi A3","2009","200","207"
['"140"', '"143"', '"202"', '"All-wheel drive"', '"Audi 3.2L 6 cylinder 250hp 236ft-lbs"', '"True"', '"6"', '"6 Speed Automatic Select Shift"', '"18"', '"Gasoline"', '"25"', '"Automatic transmission"', '"2009 Audi A3 3.2"', '"Audi"', '"2009 Audi A3"', '"2009"', '"250"', '"236"']
['"140"', '"143"', '"202"', '"Front-wheel drive"', '"Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo"', '"True"', '"6"', '"6 Speed Automatic Select Shift"', '"22"', '"Gasoline"', '"28"', '"Automatic transmission"', '"2009 Audi A3 2.0 T AT"', '"Audi"', '"2009 Audi A3"', '"2009"', '"200"', '"207"']
['"140"', '"143"', '"202"', '"Front-wheel drive"', '"Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo"', '"True"', '"6"', '"6 Speed Manual"', '"21"', '"Gasoline"', '"30"', '"Manual transmission"', '"2009 Audi A3 2.0 T"', '"Audi"', '"2009 Audi A3"', '"2009"', '"200"', '"207"']
['"140"', '"143"', '"202"', '"All-wheel drive"', '"Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo"', '"True"', '"6"', '"6 Speed Automatic Select Shift"', '"21"', '"Gasoline"', '"28"', '"Automatic transmission"', '"2009 Audi A3 2.0 T Quattro"', '"Audi"', '"2009 Audi A3"', '"2009"', '"200"', '"207"']
['"140"', '"143"', '"202"', '"All-wheel drive"', '"Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo"', '"True"', '"6"', '"6 Speed Automatic Select Shift"', '"21"', '"Gasoline"', '"28"', '"Automatic transmission"', '"2009 Audi A3 2.0 T Quattro"', '"Audi"', '"2009 Audi A3"', '"2009"', '"200"', '"207"']

ValueError: could not convert string to float: '"6 Speed Automatic Select Shift"'

In [12]:
import pandas as pd 
cars = pd.read_csv("cars.csv")
cars.head()

,Dimensions.Height,Dimensions.Length,Dimensions.Width,Engine Information.Driveline,Engine Information.Engine Type,Engine Information.Hybrid,Engine Information.Number of Forward Gears,Engine Information.Transmission,Fuel Information.City mpg,Fuel Information.Fuel Type,Fuel Information.Highway mpg,Identification.Classification,Identification.ID,Identification.Make,Identification.Model Year,Identification.Year,Engine Information.Engine Statistics.Horsepower,Engine Information.Engine Statistics.Torque
0,140,143,202,All-wheel drive,Audi 3.2L 6 cylinder 250hp 236ft-lbs,True,6,6 Speed Automatic Select Shift,18,Gasoline,25,Automatic transmission,2009 Audi A3 3.2,Audi,2009 Audi A3,2009,250,236
1,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,22,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T AT,Audi,2009 Audi A3,2009,200,207
2,140,143,202,Front-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Manual,21,Gasoline,30,Manual transmission,2009 Audi A3 2.0 T,Audi,2009 Audi A3,2009,200,207
3,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207
4,140,143,202,All-wheel drive,Audi 2.0L 4 cylinder 200 hp 207 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,21,Gasoline,28,Automatic transmission,2009 Audi A3 2.0 T Quattro,Audi,2009 Audi A3,2009,200,207

In [16]:
cars["Dimensions.Length"]

0       143
1       143
2       143
3       143
4       143
       ...
5071    253
5072    249
5073    249
5074    210
5075     94
Name: Dimensions.Length, Length: 5076, dtype: int64

In [17]:
cars.iloc[0]

Dimensions.Height                                                                   140
Dimensions.Length                                                                   143
Dimensions.Width                                                                    202
Engine Information.Driveline                                            All-wheel drive
Engine Information.Engine Type                     Audi 3.2L 6 cylinder 250hp 236ft-lbs
Engine Information.Hybrid                                                          True
Engine Information.Number of Forward Gears                                            6
Engine Information.Transmission                          6 Speed Automatic Select Shift
Fuel Information.City mpg                                                            18
Fuel Information.Fuel Type                                                     Gasoline
Fuel Information.Highway mpg                                                         25
Identification.Classification                                    Automatic transmission
Identification.ID                                                      2009 Audi A3 3.2
Identification.Make                                                                Audi
Identification.Model Year                                                  2009 Audi A3
Identification.Year                                                                2009
Engine Information.Engine Statistics.Horsepower                                     250
Engine Information.Engine Statistics.Torque                                         236
Name: 0, dtype: object

In [35]:
cars.loc[cars["Dimensions.Length"] > 150]

,Dimensions.Height,Dimensions.Length,Dimensions.Width,Engine Information.Driveline,Engine Information.Engine Type,Engine Information.Hybrid,Engine Information.Number of Forward Gears,Engine Information.Transmission,Fuel Information.City mpg,Fuel Information.Fuel Type,Fuel Information.Highway mpg,Identification.Classification,Identification.ID,Identification.Make,Identification.Model Year,Identification.Year,Engine Information.Engine Statistics.Horsepower,Engine Information.Engine Statistics.Torque
7,201,221,191,All-wheel drive,Audi 4.2L 8 cylinder 350 hp 325 ft-lbs,True,6,6 Speed Automatic Select Shift,13,Gasoline,18,Automatic transmission,2009 Audi Q7 4.2,Audi,2009 Audi Q7,2009,350,325
8,201,221,191,All-wheel drive,Audi 3.6L 6 cylinder 280hp 266 ft-lbs,True,6,6 Speed Automatic Select Shift,14,Gasoline,20,Automatic transmission,2009 Audi Q7 3.6,Audi,2009 Audi Q7,2009,280,266
14,226,243,201,All-wheel drive,BMW 4.4L 8 cylinder 555hp 500 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,12,Gasoline,17,Automatic transmission,2010 BMW X5 M SUV,BMW,2010 BMW X5,2010,555,500
15,226,243,201,All-wheel drive,BMW 4.4L 8 cylinder 555hp 500 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,12,Gasoline,17,Automatic transmission,2011 BMW X5 M SUV,BMW,2011 BMW X5,2011,555,500
36,82,215,240,Rear-wheel drive,Chevrolet 4.8L 8 Cylinder 302 hp 305 ft-lbs FFV,True,4,4 Speed Automatic,14,Gasoline,19,Automatic transmission,2011 Chevrolet Silverado 1500 Crew Cab Work Truck,Chevrolet,2011 Chevrolet Silverado 1500,2011,302,305
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5070,3,253,201,Four-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,17,Gasoline,24,Automatic transmission,2012 Honda Pilot EX 4WD,Honda,2012 Honda Pilot,2012,250,253
5071,13,253,201,Front-wheel drive,Honda 3.5L 6 Cylinder 250 hp 253 ft-lbs,True,5,5 Speed Automatic,18,Gasoline,25,Automatic transmission,2012 Honda Pilot EX-L,Honda,2012 Honda Pilot,2012,250,253
5072,141,249,108,All-wheel drive,Lamborghini 5.2L 10 cylinder 552 hp 398 ft-lbs,True,6,6 Speed Manual,12,Gasoline,20,Manual transmission,2012 Lamborghini Gallardo Coupe LP 560-4,Lamborghini,2012 Lamborghini Gallardo Coup,2012,552,398
5073,160,249,108,All-wheel drive,Lamborghini 5.2L 10 cylinder 552 hp 398 ft-lbs,True,6,6 Speed Manual,12,Gasoline,20,Manual transmission,2012 Lamborghini Gallardo LP 560-4 Spyder,Lamborghini,2012 Lamborghini Gallardo Spyder,2012,552,398
5074,200,210,110,Rear-wheel drive,BMW 3.0L 6 cylinder 315hp 330 ft-lbs Turbo,True,6,6 Speed Automatic Select Shift,17,Gasoline,25,Automatic transmission,2012 BMW 740i Sedan,BMW,2012 BMW 7 Series,2012,315,330

In [ ]:
cars["Dimensions.Length"] = cars["Dimensions.Width"] / cars["Dimensions.Height"]
cars.columns